version: '3'
 
services:

    mysql:
        image: mysql:5.7
        expose:
            - 3306
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=xone
            - MYSQL_USER=xone
            - MYSQL_PASSWORD=xone
            - MYSQL_ROOT_PASSWORD=xone
        command: mysqld --key-buffer-size=32M --max-allowed-packet=16M --myisam-recover-options=FORCE,BACKUP --tmp-table-size=32M --query-cache-type=0 --query-cache-size=0 --max-heap-table-size=32M --max-connections=500 --thread-cache-size=50 --innodb-flush-method=O_DIRECT --innodb-log-file-size=512M --innodb-buffer-pool-size=16G --open-files-limit=65535

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=Mypassword
            - MYSQL_ROOT_PASSWORD=Mypassword
        ports:
            - 8085:80

    apache_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_1
        build: ./web/1
        volumes:
            - .:/var/www/html
        expose:
            - ${APACHE_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APACHE_1_IP}
    apache_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_2
        build: ./web/2
        volumes:
            - .:/var/www/html
        expose:
            - ${APACHE_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APACHE_2_IP}

    apache_img_3:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_3
        build: ./web/3
        volumes:
            - .:/var/www/html
        expose:
            - ${APACHE_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APACHE_3_IP}

    haproxy_img:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - APACHE_1_IP=${APACHE_1_IP}
            - APACHE_2_IP=${APACHE_2_IP}
            - APACHE_3_IP=${APACHE_3_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
